### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by joerg2805** [mariolukas/cncjs-pendant-numpad#1]
Hello, I get the following error message at startup:

```javascript
pi@mpcncpi:~/cncjs-pendant-numpad $ bin/cncjs-pendant-numpad
? Specify which port you want to use? /dev/ttyACM0
{ Error: ENOENT: no such file or directory, open '/home/pi/.cncjs/cncrc.cfg'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at module.exports (/home/pi/cncjs-pendant-numpad/index.js:47:42)
    at createServer (/home/pi/cncjs-pendant-numpad/bin/cncjs-pendant-numpad:91:5)
    at /home/pi/cncjs-pendant-numpad/bin/cncjs-pendant-numpad:334:13
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/pi/.cncjs/cncrc.cfg' }

```
Any idea?

**Comment by jekhor** [comment]
It wants non-standard location of cncrc file. 
I made symlink /home/pi/.cncjs/cncrc.cfg pointed to ~/.cncrc for test.

**Comment by jekhor** [comment]
I made fork of this project for our hackerspace. Now it works.
https://github.com/minsk-hackerspace/cncjs-pendant-numpad/commit/dff409d13481f6085d2c72393b47de7f973cb1ef

**Comment by joerg2805** [comment]
Thanks very much.

**Comment by mariolukas** [comment]
great, can you  do a pull request?

**Comment by jekhor** [comment]
Sure.

сб, 15 мая 2021, 09.48 карыстальнік Mario Lukas ***@***.***>
напісаў:

**Comment by mariolukas** [comment]
tnx

**Comment by jekhor** [comment]
#2 I cleaned some device-specific key mappings from our main branch.

**Comment by mariolukas** [comment]
Just merged it.
